env:
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: tsconfig.json
  sourceType: module
  ecmaVersion: 2020
plugins:
  - "@typescript-eslint"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
settings:
  "import/resolver":
    typescript:
      directory: ./tsconfig.json
rules:
  "react/prop-types": off
  "@typescript-eslint/no-var-requires": off
  "@typescript-eslint/indent":
    - error
    - 2
  "@typescript-eslint/no-unused-vars":
    - warn
    - argsIgnorePattern: "^_"
      varsIgnorePattern: "^_+$"
  "@typescript-eslint/quotes":
    - warn
    - double
  "@typescript-eslint/explicit-module-boundary-types":
    - warn
    - allowArgumentsExplicitlyTypedAsAny: true
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/unbound-method":
    - error
    - ignoreStatic: true
